name: async_notifier
description: A ValueNotifier for all async states. Listen, notify, and manage loading, error and data in one place.
version: 0.7.0
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/async_notifier
topics:
 - async
 - value
 - notifier
 - state

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

